[tool.ruff]
line-length = 88
target-version = "py39"
exclude = [
    "**/migrations/*.py",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F"]
ignore = []

# Optional: allow autofix for everything Ruff can safely fix
fixable = ["ALL"]
unfixable = ["E501"]